### PR TITLE
Implement environment variable as a possible path source for diff tools

### LINKED ISSUE #310: Allow to set custom installation paths for supported diff tools
#### Is the feature request related to a problem
I have a custom installation folder for both VS Code and Visual studio. The search paths for these diff tools don't match with the ones hard-coded inside DiffEngine.

#### Describe the solution
One should be able to set a custom path for diff tools, for example with the help of environment variables.
For example: `DiffEngine_<DiffToolName>_Path` = `D:\My\Folder\`

#### Describe alternatives considered
As alternative, consider reading a configuration file in the home directory of the user or in the project folder.

#### Additional context
If necessary ask me.

### PR DESCRIPTION
**Pull request by ldeluigi**
Closes #310 

Given that I don't know which versions and tools are "portable", that is, installable basically anywhere, I've just set up Visual Studio Code environment variable: `DiffEngine_VisualStudioCode` for windows.

If you want more variables already set in this PR just tell me for which OS and diff tools -> var name.

### CODE REVIEW

**Comment by ldeluigi** [comment]
@SimonCropp news on this?

**Comment by SimonCropp** [comment]
you seem to have only implemented for VisualStudioCode?

**Comment by ldeluigi** [comment]
> you seem to have only implemented for VisualStudioCode?

yes, I'd like your feedback before having implemented for every single one of them

**Comment by ldeluigi** [comment]
Maybe there are some editors that can't be installed somewhere else than their default location for which this kind of option is not helpful, and given that I don't know if this is the case for the other editors I'm waiting your opinion

**Comment by ldeluigi** [comment]
@dotnet-policy-service agree

**Comment by ldeluigi** [comment]
@SimonCropp done

**Comment by SimonCropp** [comment]
can you add some docs

**Pull request merged**
